name: Swift CI - Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=14.2,name=iPhone 12 Pro Max"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Force Xcode 12.2
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app
        
      - name: Install Dependencies
        run: |
          pod repo update
          pod install
        shell: bash
      
      - name: Build devRantSwiftUI project - ${{ matrix.destination }}
        run: xcodebuild -scheme "devRantAvatarEditor - Release" -workspace devRantAvatarEditor.xcworkspace -destination "${{ matrix.destination }}" IPHONEOS_DEPLOYMENT_TARGET=14.2
